POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZhYmlhblJpdmVybyIsImlkIjoiNjcyYzQ0NWU4MjZmNzJiMjI4NmJlNDFkIiwiaWF0IjoxNzMwOTk4NzQyfQ.7il0c4Z5wYM0tuUNneuBzKmY2FOKdCa1PZvhvaxran4

{
    "title": "blog test 2",
    "author": "Fabian Rivero",
    "url": "http://test.com",
    "likes": 5,
    "user": "672c445e826f72b2286be41d" 
}